imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ MopaBootstrapBundle ]
    #java: /usr/bin/java
    filters:
        less:
            node: %node%
            node_paths: %node_paths%
            apply_to: "\.less$"
        cssrewrite:
            apply_to: "\.(?:less|css)$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mopa_bootstrap:
    form:
        render_fieldset: false
        show_legend: false
        collection:
            widget_remove_btn:
                label: Remove
                icon: remove-sign
            widget_add_btn:
                label: Add
                icon: plus-sign
    navbar: ~

fos_rest:
    view:
        view_response_listener: force
    format_listener:
        rules:
            - { priorities: [ html, json, xml, '*/*' ], fallback_format: html, prefer_extension: true }

sensio_framework_extra:
    view:    { annotations: false }

jms_rst:
    sphinx_config_dir: "%kernel.root_dir%/../source"

vich_uploader:
    db_driver: orm

ite_form:
    components:
        collection:
            enabled: true
            type: bs3
        dynamic_choice: ~
        hierarchical: ~
        ajax_file_upload:
            enabled: ~
            tmp_prefix: uploads/tmp
        editable: ~
        ordered: ~
        validation: ~
        debug: ~
    plugins:
        select2: ~
        tinymce:
            enabled: true
            options:
                script_url: '/bundles/itelibrary/plugin/tinymce/js/tinymce/tinymce.min.js'
                theme: modern
                plugins: [ advlist, anchor, autolink, autoresize, autosave, charmap, code, contextmenu, directionality, emoticons, example, example_dependency, fullscreen, hr, image, insertdatetime, layer, legacyoutput, link, lists, media, nonbreaking, noneditable, pagebreak, paste, preview, print, save, searchreplace, spellchecker, tabfocus, table, template, textcolor, visualblocks, visualchars, wordcount ] # bbcode and fullpage are skipped
        bootstrap_colorpicker: ~
        bootstrap_spinedit: ~
        bootstrap_datetimepicker:
            enabled: true
            options:
                weekStart: 1
#        bootstrap_datetimepicker2:
#            enabled: true
#            options:
#                weekStart: 1
        fileupload: ~
        fineuploader: ~
        minicolors:
            enabled: true
            options:
                theme: bootstrap
        knob: ~
        starrating: ~
        x_editable: ~
        nod: ~
        parsley: ~
        form: ~