<?php

namespace ITE\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BundlePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundlePageRepository extends EntityRepository
{
    /**
     * @param $criteria
     * @return mixed
     */
    public function findByBundleAndPath($criteria)
    {
        /** @var $bundle Bundle */
        $bundle = $criteria['bundle'];
        $path = $criteria['path'];
        if ('/' !== $path) {
            $path = rtrim($path, '/');
        }

        return $this->createQueryBuilder('bp')
            ->andWhere('bp.bundle = :bundleId')
            ->andWhere('bp.path = :path')
            ->setParameter('bundleId', $bundle->getId())
            ->setParameter('path', $path)
            ->getQuery()
            ->getSingleResult();
    }
}
