<?php

namespace ITE\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * NumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberRepository extends EntityRepository
{
    /**
     * @param $start
     * @param $end
     * @return array
     */
    public function getByIdRange($start, $end)
    {
        return $this->getByIdRangeQueryBuilder($start, $end)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $start
     * @param $end
     * @return QueryBuilder
     */
    public function getByIdRangeQueryBuilder($start, $end)
    {
        return $this->createQueryBuilder('n')
            ->andWhere('n.id BETWEEN :start AND :end')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ;
    }
}
